services:
    db:
        image: postgres:17
        restart: always
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            TZ: UTC
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

    db_test:
        image: postgres:17
        restart: always
        environment:
            POSTGRES_DB: db_test
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            TZ: UTC
        ports:
            - '5433:5432'
        volumes:
            - postgres_data_test:/var/lib/postgresql/data

volumes:
    postgres_data:
    postgres_data_test:
