services:
    db:
        image: mysql:9
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            TZ: UTC
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - '3306:3306'
    db_test:
        image: mysql:9
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_test
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            TZ: UTC
        volumes:
            - mysql_data_test:/var/lib/mysql
        ports:
            - '3307:3306'
volumes:
    mysql_data:
    mysql_data_test:
