version: '3.8'

services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mysqldb
            MYSQL_USER: mysqluser
            MYSQL_PASSWORD: mysqlpassword
            TZ: UTC
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
